modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
    modId="bounties"
    version="${file.jarVersion}"
    displayName="Bounties"
    authors="ThatGravyBoat"
    description="Claim bounties!"

[[dependencies.multiloader]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.multiloader]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
